import { defineConfig } from "drizzle-kit";

/**
 * Which database drizzle-kit talks to.
 *
 * After the dev/prod split (2026-08-16), `DATABASE_URL` in `.env` points at the
 * DEV Neon branch — that is what you want for `npm run dev` and for generating
 * and testing migrations. But production still needs those migrations applied,
 * and the failure mode is predictable: you migrate dev, deploy the code, and
 * production crashes on a column that was never created there.
 *
 * So `TARGET_DATABASE_URL` overrides when set. `npm run db:migrate:prod` sets it
 * to `PROD_DATABASE_URL` for one command — no editing `.env`, no risk of
 * forgetting to change it back, which is how people end up developing against
 * production without realising.
 */
const url = process.env.TARGET_DATABASE_URL || process.env.DATABASE_URL;

if (!url) {
  throw new Error("No database URL. Set DATABASE_URL in .env (or TARGET_DATABASE_URL for one command).");
}

export default defineConfig({
  dialect: "postgresql",
  // Every domain module owns its tables in src/modules/<domain>/schema.ts.
  // Auth tables are generated by Better Auth into src/db/auth-schema.ts.
  schema: ["./src/modules/**/schema.ts", "./src/db/auth-schema.ts"],
  out: "./drizzle",
  dbCredentials: { url },
  strict: true,
  verbose: true,
});
