import { defineConfig } from "drizzle-kit";

export default defineConfig({
  dialect: "postgresql",
  // Every domain module owns its tables in src/modules/<domain>/schema.ts.
  // Auth tables are generated by Better Auth into src/db/auth-schema.ts.
  schema: ["./src/modules/**/schema.ts", "./src/db/auth-schema.ts"],
  out: "./drizzle",
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
  strict: true,
  verbose: true,
});
