/**
 * Barrel: aggregates every module's tables so db.query.* and drizzle-kit
 * see one schema. Add a line here when a new module lands — nothing else
 * in existing modules changes (modularity rule).
 */
export * from "../modules/branches/schema";
export * from "../modules/staff/schema";
export * from "../modules/inventory/schema";
export * from "../modules/customers/schema";
export * from "../modules/visitors/schema";
export * from "../modules/testdrives/schema";
export * from "../modules/sales/schema";
export * from "../modules/installment-plans/schema";
export * from "../modules/document-requirements/schema";
export * from "../modules/ledger/schema";
export * from "../modules/bookings/schema";
export * from "../modules/parts/schema";
export * from "../modules/gatepass/schema";
export * from "../modules/workshop/schema";
export * from "../modules/hr/schema";
export * from "../modules/procurement/schema";
export * from "../modules/audit/schema";
export * from "./auth-schema"; // generated by `npm run auth:generate`
