/**
 * Barrel: aggregates every module's tables so db.query.* and drizzle-kit
 * see one schema. Add a line here when a new module lands — nothing else
 * in existing modules changes (modularity rule).
 */
export * from "../modules/branches/schema";
export * from "../modules/staff/schema";
export * from "../modules/inventory/schema";
export * from "../modules/customers/schema";
export * from "../modules/sales/schema";
export * from "../modules/ledger/schema";
export * from "../modules/audit/schema";
export * from "./auth-schema"; // generated by `npm run auth:generate`
