import { redirect } from "next/navigation";
import { APP_NAME } from "@/lib/config";
import { getMonthlyPnl } from "@/modules/reports/queries";
import { listActiveBranches } from "@/modules/inventory/queries";
import { requireStaff } from "@/lib/session";
import { PrintButton } from "../../sales/[id]/print-button";

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

export default async function PnlPage({
  searchParams,
}: {
  searchParams: Promise<{ y?: string; m?: string; branch?: string }>;
}) {
  const { profile } = await requireStaff();
  if (!["creator", "owner", "silent_partner"].includes(profile.role)) redirect("/dashboard");

  const params = await searchParams;
  const now = new Date();
  const year = params.y ? Number(params.y) : now.getFullYear();
  const month = params.m ? Number(params.m) : now.getMonth() + 1;
  const branchId = params.branch ? Number(params.branch) : undefined;

  const [pnl, branches] = await Promise.all([
    getMonthlyPnl({ year, month, branchId }),
    listActiveBranches(),
  ]);

  const fmt = (v: number) =>
    `${v < 0 ? "−" : ""}Rs. ${Math.abs(v).toLocaleString("en-PK", { timeZone: "Asia/Karachi", maximumFractionDigits: 0 })}`;
  const branchName = branchId ? branches.find((b) => b.id === branchId)?.name : "All Branches";
  const years = [now.getFullYear() - 1, now.getFullYear()];

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <div className="flex items-center justify-between print:hidden">
        <h1 className="text-xl font-semibold">Profit & Loss Statement</h1>
        <PrintButton />
      </div>

      <form method="get" className="flex flex-wrap gap-3 print:hidden">
        <select name="m" defaultValue={String(month)} className="rounded-lg border border-line bg-surface px-3 py-1.5 text-sm">
          {MONTHS.map((name, i) => (
            <option key={name} value={i + 1}>{name}</option>
          ))}
        </select>
        <select name="y" defaultValue={String(year)} className="rounded-lg border border-line bg-surface px-3 py-1.5 text-sm">
          {years.map((yy) => (
            <option key={yy} value={yy}>{yy}</option>
          ))}
        </select>
        <select name="branch" defaultValue={params.branch ?? ""} className="rounded-lg border border-line bg-surface px-3 py-1.5 text-sm">
          <option value="">All branches</option>
          {branches.map((b) => (
            <option key={b.id} value={b.id}>{b.name}</option>
          ))}
        </select>
        <button className="rounded-lg bg-brand-600 px-4 py-1.5 text-sm text-white hover:bg-brand-500">
          Compile
        </button>
      </form>

      <div className="card p-8 print:border-0 print:p-0">
        <div className="mb-6 text-center">
          <h2 className="text-lg font-bold">Profit and Loss Statement</h2>
          <p className="text-sm text-ink-faint">
            {MONTHS[month - 1]} {year} · {branchName} · {pnl.invoiceCount} sale{pnl.invoiceCount === 1 ? "" : "s"}
          </p>
        </div>

        <Section title="Operating Revenue">
          <Line k="Vehicle sales (net of discounts)" v={fmt(pnl.netSales)} />
          <Line k="Registration fee profit" v={fmt(pnl.regProfit)} />
          <Line k="Installment markup (booked at sale)" v={fmt(pnl.markup)} />
          <Total k="Total Revenue (A)" v={fmt(pnl.revenue)} />
        </Section>

        <Section title="Cost of Sales">
          <Line k="Cost of vehicles sold (COGS)" v={fmt(pnl.cogs)} />
          <Total k="Gross Profit (B = A − COGS)" v={fmt(pnl.grossProfit)} highlight={pnl.grossProfit >= 0 ? "pos" : "neg"} />
        </Section>

        <Section title="Operating Expenses">
          {pnl.expenses.length === 0 && <Line k="No expenses recorded this month" v="—" />}
          {pnl.expenses.map((e) => (
            <Line key={e.category} k={e.category} v={fmt(e.total)} cap />
          ))}
          <Line k="Salesperson commissions" v={fmt(pnl.commissions)} />
          <Total k="Total Expenses (C)" v={fmt(pnl.totalExpenses + pnl.commissions)} />
        </Section>

        <div className={`mt-6 rounded-lg p-4 ${pnl.netProfit >= 0 ? "bg-emerald-50" : "bg-red-50"}`}>
          <div className={`flex justify-between text-lg font-bold ${pnl.netProfit >= 0 ? "text-emerald-700" : "text-red-700"}`}>
            <span>NET {pnl.netProfit >= 0 ? "PROFIT" : "LOSS"} (B − C)</span>
            <span>{fmt(pnl.netProfit)}</span>
          </div>
        </div>

        <p className="mt-6 text-xs text-ink-faint">
          Markup is recognized in the month of sale. Stock purchases are assets, not expenses, and are excluded here.
          Generated by {APP_NAME} · {new Date().toLocaleDateString("en-PK", { timeZone: "Asia/Karachi" })}
        </p>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-6">
      <h3 className="mb-2 border-b border-line pb-1 text-xs font-semibold uppercase tracking-wide text-ink-faint">
        {title}
      </h3>
      <div className="space-y-1.5 text-sm">{children}</div>
    </div>
  );
}

function Line({ k, v, cap }: { k: string; v: string; cap?: boolean }) {
  return (
    <div className="flex justify-between text-ink-soft">
      <span className={cap ? "capitalize" : ""}>{k}</span>
      <span>{v}</span>
    </div>
  );
}

function Total({ k, v, highlight }: { k: string; v: string; highlight?: "pos" | "neg" }) {
  const color = highlight === "pos" ? "text-emerald-700" : highlight === "neg" ? "text-red-700" : "";
  return (
    <div className={`flex justify-between border-t border-line pt-1.5 font-semibold ${color}`}>
      <span>{k}</span>
      <span>{v}</span>
    </div>
  );
}
