# ONE-SHOT COMMIT & PUSH - regenerated by Claude at every checkpoint.
# Run from the repo root:  powershell -ExecutionPolicy Bypass -File .\scripts\push.ps1
# NOTE: this file must stay ASCII-only (PowerShell 5.1 reads ps1 as ANSI).

function Commit($msg, $paths, $date = $null) {
  git add $paths 2>$null
  git diff --cached --quiet
  if ($LASTEXITCODE -ne 0) {
    if ($date) { $env:GIT_AUTHOR_DATE = $date; $env:GIT_COMMITTER_DATE = $date }
    else { Remove-Item Env:GIT_AUTHOR_DATE -ErrorAction SilentlyContinue; Remove-Item Env:GIT_COMMITTER_DATE -ErrorAction SilentlyContinue }
    git commit -m $msg
    Write-Host ("  OK  " + $msg) -ForegroundColor Green
  } else {
    Write-Host ("  --  skipped (no changes): " + $msg) -ForegroundColor DarkGray
  }
}

Write-Host "Hussain Motors ERP - endgame checkpoint push" -ForegroundColor Cyan

Commit "Accounting: journal, trial balance, balance sheet queries" @("src/modules/accounting")
Commit "Accounting page: tabbed statements with integrity checks" @("src/app/(dashboard)/accounting")
Commit "Fixed assets: schema and service" @("src/modules/assets", "src/db/schema.ts")
Commit "Fixed assets register page" @("src/app/(dashboard)/assets")
Commit "Silent Partner role: enum + read-only permission sweep" @("src/modules/staff/schema.ts", "src/lib/session.ts", "src/modules/inventory/permissions.ts", "src/modules/customers/permissions.ts", "src/modules/sales/permissions.ts", "src/modules/ledger/permissions.ts", "src/modules/bookings/permissions.ts", "src/modules/parts/service.ts")
Commit "Silent Partner: staff onboarding + sidebar + page gates" @("src/modules/staff/service.ts", "src/app/(dashboard)/staff", "src/components/sidebar.tsx", "src/app/(dashboard)/reports")
Commit "Email layer: Resend client + recipient policy + high-priority hook" @("src/lib/email.ts", "src/modules/notifications/email.ts", "src/lib/audit.ts")
Commit "Daily and monthly email reports per branch" @("src/modules/reports/email-reports.ts")
Commit "Cron endpoints for scheduled reports" @("src/app/api/cron")
Commit "Settings: send-test-report buttons" @("src/app/(dashboard)/system-settings")
Commit "Test data seeder through real services" @("scripts/seed-test-data.ts", "package.json")
Commit "System test plan (TESTING.md)" @("TESTING.md")
Commit "Env template: resend + cron secrets" @(".env.example")
Commit "Migration: silent_partner, branch_assets, and friends" @("drizzle")
Commit "Roadmap + handover: endgame complete" @("ROADMAP.md", "HANDOVER.md", "scripts/push.ps1")
Commit "Chores: remaining pending files" @(".")

Remove-Item Env:GIT_AUTHOR_DATE -ErrorAction SilentlyContinue
Remove-Item Env:GIT_COMMITTER_DATE -ErrorAction SilentlyContinue

git push origin main
Write-Host "Done - pushed to main (Railway deploys automatically)." -ForegroundColor Cyan
